/**
 * Semantic Event Types
 *
 * Reusable event vocabulary for all algorithm step generators.
 * The UI decides how each event should look — the algorithm only
 * emits semantic actions.
 */
export const EVENT_TYPES = {
  INITIALIZE: "initialize",
  COMPARE: "compare",
  SWAP: "swap",
  MOVE: "move",
  SELECT: "select",
  UPDATE: "update",
  INSERT: "insert",
  DELETE: "delete",
  VISIT: "visit",
  ENQUEUE: "enqueue",
  DEQUEUE: "dequeue",
  PUSH: "push",
  POP: "pop",
  RELAX: "relax",
  ACCEPT: "accept",
  REJECT: "reject",
  SPLIT: "split",
  MERGE: "merge",
  CALCULATE: "calculate",
  COMPLETE: "complete",

  /* ── Extended events used by specific algorithms ── */

  // Array patterns
  COMPARE_POINTERS: "compare_pointers",
  MOVE_LEFT: "move_left",
  MOVE_RIGHT: "move_right",
  FOUND: "found",
  NOT_FOUND: "not_found",
  ADD_TO_WINDOW: "add_to_window",
  SLIDE_WINDOW: "slide_window",
  REMOVE_FROM_WINDOW: "remove_from_window",
  UPDATE_BEST: "update_best",
  BUILD_PREFIX: "build_prefix",
  SELECT_RANGE: "select_range",
  CALCULATE_RANGE: "calculate_range",
  COMPARE_EXTEND_OR_RESTART: "compare_extend_or_restart",
  UPDATE_CURRENT: "update_current",

  // Sorting
  MARK_SORTED: "mark_sorted",
  SELECT_POSITION: "select_position",
  SELECT_MINIMUM: "select_minimum",
  UPDATE_MINIMUM: "update_minimum",
  SELECT_KEY: "select_key",
  SHIFT: "shift",
  INSERT_KEY: "insert_key",
  TAKE_LEFT: "take_left",
  TAKE_RIGHT: "take_right",
  SELECT_PIVOT: "select_pivot",
  MOVE_TO_LEFT_PARTITION: "move_to_left_partition",
  PLACE_PIVOT: "place_pivot",
  PARTITION_COMPLETE: "partition_complete",
  COMPARE_PARENT_CHILD: "compare_parent_child",
  SWAP_HEAP: "swap_heap",
  HEAPIFY: "heapify",
  EXTRACT_MAX: "extract_max",

  // Linked List
  CREATE_NODE: "create_node",
  CHECK_HEAD: "check_head",
  MOVE_CURRENT: "move_current",
  LINK_NODE: "link_node",
  SET_NEXT: "set_next",
  SET_PREV: "set_prev",
  CLOSE_CIRCLE: "close_circle",
  MOVE_SLOW: "move_slow",
  MOVE_FAST: "move_fast",

  // Stack
  PEEK: "peek",
  RESOLVE_NEXT_GREATER: "resolve_next_greater",

  // Tree
  ENTER_NODE: "enter_node",
  GO_LEFT: "go_left",
  GO_RIGHT: "go_right",
  RETURN: "return",
  BACKTRACK: "backtrack",
  ENQUEUE_LEFT: "enqueue_left",
  ENQUEUE_RIGHT: "enqueue_right",

  // Graph
  EXPLORE_EDGE: "explore_edge",
  CALCULATE_INDEGREE: "calculate_indegree",
  ENQUEUE_ZERO_INDEGREE: "enqueue_zero_indegree",
  REMOVE_EDGE: "remove_edge",
  DECREMENT_INDEGREE: "decrement_indegree",
  INITIALIZE_SETS: "initialize_sets",
  FIND: "find",
  COMPARE_ROOTS: "compare_roots",
  UNION: "union",
  PATH_COMPRESSION: "path_compression",
  CONNECTED: "connected",
  INITIALIZE_DISTANCES: "initialize_distances",
  EXTRACT_MIN: "extract_min",
  CALCULATE_DISTANCE: "calculate_distance",
  UPDATE_DISTANCE: "update_distance",
  SORT_EDGES: "sort_edges",
  SELECT_EDGE: "select_edge",
  CHECK_CYCLE: "check_cycle",
  ACCEPT_EDGE: "accept_edge",
  REJECT_EDGE: "reject_edge",
  UPDATE_MST: "update_mst",

  // DP
  USE_PREVIOUS_STATE: "use_previous_state",
  UPDATE_CELL: "update_cell",
  INITIALIZE_GRID: "initialize_grid",
  CALCULATE_CELL: "calculate_cell",
  READ_TOP: "read_top",
  READ_LEFT: "read_left",
  CONSIDER_ITEM: "consider_item",
  SKIP: "skip",
  TAKE: "take",
  EXTEND: "extend",
  UPDATE_DP: "update_dp",
  RECONSTRUCT: "reconstruct",
  COMPARE_CHARACTERS: "compare_characters",
  MATCH: "match",
  USE_DIAGONAL: "use_diagonal",
  MISMATCH: "mismatch",
  CHOOSE_TOP_OR_LEFT: "choose_top_or_left",
  SELECT_INTERVAL: "select_interval",
  TRY_SPLIT: "try_split",
  CALCULATE_COST: "calculate_cost",
  COMPARE_COST: "compare_cost",
};
